from __future__ import annotations

from importlib import import_module
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from .analytics import (
        BrandAnalytics,
        BrandAnalyticsShareOfVoice,
        BrandAnalyticsTotals,
        BrandAnalyticsVisibility,
        BrandQueryFanout,
        CitationDomain,
        CitationDomainCategory,
        CitationDomainList,
        CitationDomainListTotals,
        CitationURL,
        CitationURLCategory,
        CitationURLList,
        CitationURLListTotals,
        CitationURLPageType,
        DateRange,
        FanoutQuery,
        GetBrandAnalyticsResponse,
        GetBrandQueryFanoutResponse,
        ListBrandCitationDomainsResponse,
        ListBrandCitationURLsResponse,
        ListBrandPromptPerformanceResponse,
        ModelVisibility,
        PromptPerformance,
        PromptPerformanceList,
        ShareOfVoiceEntry,
        ShareOfVoicePoint,
        VisibilityPoint,
    )
    from .brands import (
        Brand,
        BrandsList,
        CreateBrandRequest,
        CreateBrandRequestCompetitorsItem,
        CreateBrandRequestCompetitorsItemDict,
        CreateBrandRequestPromptsItem,
        CreateBrandRequestPromptsItemDict,
        CreateBrandResponse,
        GetBrandResponse,
        UpdateBrandRequest,
        UpdateBrandResponse,
    )
    from .competitors import (
        Competitor,
        CompetitorsList,
        CreateCompetitorRequest,
        CreateCompetitorResponse,
        DeleteCompetitorResponse,
        GetCompetitorResponse,
        UpdateCompetitorRequest,
        UpdateCompetitorResponse,
    )
    from .identity import (
        APIKeyIdentity,
        APIKeyIdentityKeyType,
        APIKeyIdentityRateLimit,
        APIKeyIdentityRateLimitWindow,
        APIKeyIdentityScopesItem,
        GetMeResponse,
    )
    from .models import ListModelsResponse, Model, ModelList
    from .opportunities import (
        BrandOpportunities,
        BrandOpportunitiesStatus,
        CitedPage,
        GetBrandOpportunitiesResponse,
        Opportunity,
        OpportunityCategory,
        OpportunityPrompt,
    )
    from .organizations import (
        BillingPlan,
        BillingPlanInterval,
        BillingPlanStanding,
        GetOrganizationBillingResponse,
        GetOrganizationResponse,
        Organization,
        OrganizationBilling,
        OrganizationBillingUsage,
        OrganizationList,
        PlanLimits,
    )
    from .prompts import (
        CreatePromptRequest,
        CreatePromptResponse,
        DeletePromptResponse,
        GetPromptResponse,
        Prompt,
        UpdatePromptRequest,
        UpdatePromptResponse,
    )
    from .reports import (
        CreateReportRequest,
        CreateReportResponse,
        CreateReportStatus,
        GetReportResponse,
        GetReportStatus,
        GetReportUnstable,
        GetReportUnstableCompetitorsItem,
        ReportPromptSnapshot,
        ReportSummary,
        ReportSummaryStatus,
    )
    from .runs import GetRunResponse, Run, RunAnswer, RunCitation, RunList, RunSummary
    from .shared import Error, MentionEntry, MentionsSummary, OpenEnum, Pagination
    from .snapshots import (
        CitedURLEntry,
        GetPromptSnapshotResponse,
        PromptSnapshot,
        PromptSnapshotCitations,
    )
    from .tags import ListBrandTagsResponse, Tag, TagList
    from .tools import (
        AnalyzeBrandRequest,
        AnalyzeBrandResponse,
        OnboardingSuggestion,
        OnboardingSuggestionCompetitorsItem,
        OnboardingSuggestionSuggestedPromptsItem,
    )

__all__ = [
    "APIKeyIdentity",
    "APIKeyIdentityKeyType",
    "APIKeyIdentityRateLimit",
    "APIKeyIdentityRateLimitWindow",
    "APIKeyIdentityScopesItem",
    "AnalyzeBrandRequest",
    "AnalyzeBrandResponse",
    "BillingPlan",
    "BillingPlanInterval",
    "BillingPlanStanding",
    "Brand",
    "BrandAnalytics",
    "BrandAnalyticsShareOfVoice",
    "BrandAnalyticsTotals",
    "BrandAnalyticsVisibility",
    "BrandOpportunities",
    "BrandOpportunitiesStatus",
    "BrandQueryFanout",
    "BrandsList",
    "CitationDomain",
    "CitationDomainCategory",
    "CitationDomainList",
    "CitationDomainListTotals",
    "CitationURL",
    "CitationURLCategory",
    "CitationURLList",
    "CitationURLListTotals",
    "CitationURLPageType",
    "CitedPage",
    "CitedURLEntry",
    "Competitor",
    "CompetitorsList",
    "CreateBrandRequest",
    "CreateBrandRequestCompetitorsItem",
    "CreateBrandRequestCompetitorsItemDict",
    "CreateBrandRequestPromptsItem",
    "CreateBrandRequestPromptsItemDict",
    "CreateBrandResponse",
    "CreateCompetitorRequest",
    "CreateCompetitorResponse",
    "CreatePromptRequest",
    "CreatePromptResponse",
    "CreateReportRequest",
    "CreateReportResponse",
    "CreateReportStatus",
    "DateRange",
    "DeleteCompetitorResponse",
    "DeletePromptResponse",
    "Error",
    "FanoutQuery",
    "GetBrandAnalyticsResponse",
    "GetBrandOpportunitiesResponse",
    "GetBrandQueryFanoutResponse",
    "GetBrandResponse",
    "GetCompetitorResponse",
    "GetMeResponse",
    "GetOrganizationBillingResponse",
    "GetOrganizationResponse",
    "GetPromptResponse",
    "GetPromptSnapshotResponse",
    "GetReportResponse",
    "GetReportStatus",
    "GetReportUnstable",
    "GetReportUnstableCompetitorsItem",
    "GetRunResponse",
    "ListBrandCitationDomainsResponse",
    "ListBrandCitationURLsResponse",
    "ListBrandPromptPerformanceResponse",
    "ListBrandTagsResponse",
    "ListModelsResponse",
    "MentionEntry",
    "MentionsSummary",
    "Model",
    "ModelList",
    "ModelVisibility",
    "OnboardingSuggestion",
    "OnboardingSuggestionCompetitorsItem",
    "OnboardingSuggestionSuggestedPromptsItem",
    "OpenEnum",
    "Opportunity",
    "OpportunityCategory",
    "OpportunityPrompt",
    "Organization",
    "OrganizationBilling",
    "OrganizationBillingUsage",
    "OrganizationList",
    "Pagination",
    "PlanLimits",
    "Prompt",
    "PromptPerformance",
    "PromptPerformanceList",
    "PromptSnapshot",
    "PromptSnapshotCitations",
    "ReportPromptSnapshot",
    "ReportSummary",
    "ReportSummaryStatus",
    "Run",
    "RunAnswer",
    "RunCitation",
    "RunList",
    "RunSummary",
    "ShareOfVoiceEntry",
    "ShareOfVoicePoint",
    "Tag",
    "TagList",
    "UpdateBrandRequest",
    "UpdateBrandResponse",
    "UpdateCompetitorRequest",
    "UpdateCompetitorResponse",
    "UpdatePromptRequest",
    "UpdatePromptResponse",
    "VisibilityPoint",
]


_LAZY_EXPORTS = {
    "APIKeyIdentity": (".identity", "APIKeyIdentity"),
    "APIKeyIdentityKeyType": (".identity", "APIKeyIdentityKeyType"),
    "APIKeyIdentityRateLimit": (".identity", "APIKeyIdentityRateLimit"),
    "APIKeyIdentityRateLimitWindow": (".identity", "APIKeyIdentityRateLimitWindow"),
    "APIKeyIdentityScopesItem": (".identity", "APIKeyIdentityScopesItem"),
    "AnalyzeBrandRequest": (".tools", "AnalyzeBrandRequest"),
    "AnalyzeBrandResponse": (".tools", "AnalyzeBrandResponse"),
    "BillingPlan": (".organizations", "BillingPlan"),
    "BillingPlanInterval": (".organizations", "BillingPlanInterval"),
    "BillingPlanStanding": (".organizations", "BillingPlanStanding"),
    "Brand": (".brands", "Brand"),
    "BrandAnalytics": (".analytics", "BrandAnalytics"),
    "BrandAnalyticsShareOfVoice": (".analytics", "BrandAnalyticsShareOfVoice"),
    "BrandAnalyticsTotals": (".analytics", "BrandAnalyticsTotals"),
    "BrandAnalyticsVisibility": (".analytics", "BrandAnalyticsVisibility"),
    "BrandOpportunities": (".opportunities", "BrandOpportunities"),
    "BrandOpportunitiesStatus": (".opportunities", "BrandOpportunitiesStatus"),
    "BrandQueryFanout": (".analytics", "BrandQueryFanout"),
    "BrandsList": (".brands", "BrandsList"),
    "CitationDomain": (".analytics", "CitationDomain"),
    "CitationDomainCategory": (".analytics", "CitationDomainCategory"),
    "CitationDomainList": (".analytics", "CitationDomainList"),
    "CitationDomainListTotals": (".analytics", "CitationDomainListTotals"),
    "CitationURL": (".analytics", "CitationURL"),
    "CitationURLCategory": (".analytics", "CitationURLCategory"),
    "CitationURLList": (".analytics", "CitationURLList"),
    "CitationURLListTotals": (".analytics", "CitationURLListTotals"),
    "CitationURLPageType": (".analytics", "CitationURLPageType"),
    "CitedPage": (".opportunities", "CitedPage"),
    "CitedURLEntry": (".snapshots", "CitedURLEntry"),
    "Competitor": (".competitors", "Competitor"),
    "CompetitorsList": (".competitors", "CompetitorsList"),
    "CreateBrandRequest": (".brands", "CreateBrandRequest"),
    "CreateBrandRequestCompetitorsItem": (
        ".brands",
        "CreateBrandRequestCompetitorsItem",
    ),
    "CreateBrandRequestCompetitorsItemDict": (
        ".brands",
        "CreateBrandRequestCompetitorsItemDict",
    ),
    "CreateBrandRequestPromptsItem": (".brands", "CreateBrandRequestPromptsItem"),
    "CreateBrandRequestPromptsItemDict": (
        ".brands",
        "CreateBrandRequestPromptsItemDict",
    ),
    "CreateBrandResponse": (".brands", "CreateBrandResponse"),
    "CreateCompetitorRequest": (".competitors", "CreateCompetitorRequest"),
    "CreateCompetitorResponse": (".competitors", "CreateCompetitorResponse"),
    "CreatePromptRequest": (".prompts", "CreatePromptRequest"),
    "CreatePromptResponse": (".prompts", "CreatePromptResponse"),
    "CreateReportRequest": (".reports", "CreateReportRequest"),
    "CreateReportResponse": (".reports", "CreateReportResponse"),
    "CreateReportStatus": (".reports", "CreateReportStatus"),
    "DateRange": (".analytics", "DateRange"),
    "DeleteCompetitorResponse": (".competitors", "DeleteCompetitorResponse"),
    "DeletePromptResponse": (".prompts", "DeletePromptResponse"),
    "Error": (".shared", "Error"),
    "FanoutQuery": (".analytics", "FanoutQuery"),
    "GetBrandAnalyticsResponse": (".analytics", "GetBrandAnalyticsResponse"),
    "GetBrandOpportunitiesResponse": (
        ".opportunities",
        "GetBrandOpportunitiesResponse",
    ),
    "GetBrandQueryFanoutResponse": (".analytics", "GetBrandQueryFanoutResponse"),
    "GetBrandResponse": (".brands", "GetBrandResponse"),
    "GetCompetitorResponse": (".competitors", "GetCompetitorResponse"),
    "GetMeResponse": (".identity", "GetMeResponse"),
    "GetOrganizationBillingResponse": (
        ".organizations",
        "GetOrganizationBillingResponse",
    ),
    "GetOrganizationResponse": (".organizations", "GetOrganizationResponse"),
    "GetPromptResponse": (".prompts", "GetPromptResponse"),
    "GetPromptSnapshotResponse": (".snapshots", "GetPromptSnapshotResponse"),
    "GetReportResponse": (".reports", "GetReportResponse"),
    "GetReportStatus": (".reports", "GetReportStatus"),
    "GetReportUnstable": (".reports", "GetReportUnstable"),
    "GetReportUnstableCompetitorsItem": (
        ".reports",
        "GetReportUnstableCompetitorsItem",
    ),
    "GetRunResponse": (".runs", "GetRunResponse"),
    "ListBrandCitationDomainsResponse": (
        ".analytics",
        "ListBrandCitationDomainsResponse",
    ),
    "ListBrandCitationURLsResponse": (".analytics", "ListBrandCitationURLsResponse"),
    "ListBrandPromptPerformanceResponse": (
        ".analytics",
        "ListBrandPromptPerformanceResponse",
    ),
    "ListBrandTagsResponse": (".tags", "ListBrandTagsResponse"),
    "ListModelsResponse": (".models", "ListModelsResponse"),
    "MentionEntry": (".shared", "MentionEntry"),
    "MentionsSummary": (".shared", "MentionsSummary"),
    "Model": (".models", "Model"),
    "ModelList": (".models", "ModelList"),
    "ModelVisibility": (".analytics", "ModelVisibility"),
    "OnboardingSuggestion": (".tools", "OnboardingSuggestion"),
    "OnboardingSuggestionCompetitorsItem": (
        ".tools",
        "OnboardingSuggestionCompetitorsItem",
    ),
    "OnboardingSuggestionSuggestedPromptsItem": (
        ".tools",
        "OnboardingSuggestionSuggestedPromptsItem",
    ),
    "OpenEnum": (".shared", "OpenEnum"),
    "Opportunity": (".opportunities", "Opportunity"),
    "OpportunityCategory": (".opportunities", "OpportunityCategory"),
    "OpportunityPrompt": (".opportunities", "OpportunityPrompt"),
    "Organization": (".organizations", "Organization"),
    "OrganizationBilling": (".organizations", "OrganizationBilling"),
    "OrganizationBillingUsage": (".organizations", "OrganizationBillingUsage"),
    "OrganizationList": (".organizations", "OrganizationList"),
    "Pagination": (".shared", "Pagination"),
    "PlanLimits": (".organizations", "PlanLimits"),
    "Prompt": (".prompts", "Prompt"),
    "PromptPerformance": (".analytics", "PromptPerformance"),
    "PromptPerformanceList": (".analytics", "PromptPerformanceList"),
    "PromptSnapshot": (".snapshots", "PromptSnapshot"),
    "PromptSnapshotCitations": (".snapshots", "PromptSnapshotCitations"),
    "ReportPromptSnapshot": (".reports", "ReportPromptSnapshot"),
    "ReportSummary": (".reports", "ReportSummary"),
    "ReportSummaryStatus": (".reports", "ReportSummaryStatus"),
    "Run": (".runs", "Run"),
    "RunAnswer": (".runs", "RunAnswer"),
    "RunCitation": (".runs", "RunCitation"),
    "RunList": (".runs", "RunList"),
    "RunSummary": (".runs", "RunSummary"),
    "ShareOfVoiceEntry": (".analytics", "ShareOfVoiceEntry"),
    "ShareOfVoicePoint": (".analytics", "ShareOfVoicePoint"),
    "Tag": (".tags", "Tag"),
    "TagList": (".tags", "TagList"),
    "UpdateBrandRequest": (".brands", "UpdateBrandRequest"),
    "UpdateBrandResponse": (".brands", "UpdateBrandResponse"),
    "UpdateCompetitorRequest": (".competitors", "UpdateCompetitorRequest"),
    "UpdateCompetitorResponse": (".competitors", "UpdateCompetitorResponse"),
    "UpdatePromptRequest": (".prompts", "UpdatePromptRequest"),
    "UpdatePromptResponse": (".prompts", "UpdatePromptResponse"),
    "VisibilityPoint": (".analytics", "VisibilityPoint"),
}


if not TYPE_CHECKING:

    def __getattr__(name: str) -> object:
        if name not in _LAZY_EXPORTS:
            raise AttributeError(f"module {__name__} has no attribute {name}")
        module, attribute = _LAZY_EXPORTS[name]
        value = getattr(import_module(module, __name__), attribute)
        globals()[name] = value
        return value


def __dir__() -> list[str]:
    return list(__all__)
