from __future__ import annotations

from importlib import import_module
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from .analytics import (
        Analytics,
        AnalyticsWithResponse,
        AsyncAnalytics,
        AsyncAnalyticsWithResponse,
        AsyncCitations,
        AsyncCitationsWithResponse,
        AsyncDomains,
        AsyncDomainsWithResponse,
        AsyncPromptPerformance,
        AsyncPromptPerformanceWithResponse,
        AsyncQueryFanout,
        AsyncQueryFanoutWithResponse,
        AsyncURLs,
        AsyncURLsWithResponse,
        Citations,
        CitationsWithResponse,
        Domains,
        DomainsWithResponse,
        PromptPerformance,
        PromptPerformanceWithResponse,
        QueryFanout,
        QueryFanoutWithResponse,
        URLs,
        URLsWithResponse,
    )
    from .brands import AsyncBrands, AsyncBrandsWithResponse, Brands, BrandsWithResponse
    from .competitors import (
        AsyncCompetitors,
        AsyncCompetitorsWithResponse,
        Competitors,
        CompetitorsWithResponse,
    )
    from .identity import AsyncMe, AsyncMeWithResponse, Me, MeWithResponse
    from .models import AsyncModels, AsyncModelsWithResponse, Models, ModelsWithResponse
    from .opportunities import (
        AsyncOpportunities,
        AsyncOpportunitiesWithResponse,
        Opportunities,
        OpportunitiesWithResponse,
    )
    from .organizations import (
        AsyncBilling,
        AsyncBillingWithResponse,
        AsyncOrganizations,
        AsyncOrganizationsWithResponse,
        Billing,
        BillingWithResponse,
        Organizations,
        OrganizationsWithResponse,
    )
    from .prompts import (
        AsyncPrompts,
        AsyncPromptsWithResponse,
        Prompts,
        PromptsWithResponse,
    )
    from .reports import (
        AsyncReports,
        AsyncReportsWithResponse,
        Reports,
        ReportsWithResponse,
    )
    from .runs import AsyncRuns, AsyncRunsWithResponse, Runs, RunsWithResponse
    from .shared import AsyncRequestOptions, RequestOptions
    from .snapshots import (
        AsyncSnapshot,
        AsyncSnapshotWithResponse,
        Snapshot,
        SnapshotWithResponse,
    )
    from .tags import AsyncTags, AsyncTagsWithResponse, Tags, TagsWithResponse
    from .tools import AsyncTools, AsyncToolsWithResponse, Tools, ToolsWithResponse

__all__ = [
    "Analytics",
    "AnalyticsWithResponse",
    "AsyncAnalytics",
    "AsyncAnalyticsWithResponse",
    "AsyncBilling",
    "AsyncBillingWithResponse",
    "AsyncBrands",
    "AsyncBrandsWithResponse",
    "AsyncCitations",
    "AsyncCitationsWithResponse",
    "AsyncCompetitors",
    "AsyncCompetitorsWithResponse",
    "AsyncDomains",
    "AsyncDomainsWithResponse",
    "AsyncMe",
    "AsyncMeWithResponse",
    "AsyncModels",
    "AsyncModelsWithResponse",
    "AsyncOpportunities",
    "AsyncOpportunitiesWithResponse",
    "AsyncOrganizations",
    "AsyncOrganizationsWithResponse",
    "AsyncPromptPerformance",
    "AsyncPromptPerformanceWithResponse",
    "AsyncPrompts",
    "AsyncPromptsWithResponse",
    "AsyncQueryFanout",
    "AsyncQueryFanoutWithResponse",
    "AsyncReports",
    "AsyncReportsWithResponse",
    "AsyncRequestOptions",
    "AsyncRuns",
    "AsyncRunsWithResponse",
    "AsyncSnapshot",
    "AsyncSnapshotWithResponse",
    "AsyncTags",
    "AsyncTagsWithResponse",
    "AsyncTools",
    "AsyncToolsWithResponse",
    "AsyncURLs",
    "AsyncURLsWithResponse",
    "Billing",
    "BillingWithResponse",
    "Brands",
    "BrandsWithResponse",
    "Citations",
    "CitationsWithResponse",
    "Competitors",
    "CompetitorsWithResponse",
    "Domains",
    "DomainsWithResponse",
    "Me",
    "MeWithResponse",
    "Models",
    "ModelsWithResponse",
    "Opportunities",
    "OpportunitiesWithResponse",
    "Organizations",
    "OrganizationsWithResponse",
    "PromptPerformance",
    "PromptPerformanceWithResponse",
    "Prompts",
    "PromptsWithResponse",
    "QueryFanout",
    "QueryFanoutWithResponse",
    "Reports",
    "ReportsWithResponse",
    "RequestOptions",
    "Runs",
    "RunsWithResponse",
    "Snapshot",
    "SnapshotWithResponse",
    "Tags",
    "TagsWithResponse",
    "Tools",
    "ToolsWithResponse",
    "URLs",
    "URLsWithResponse",
]


_LAZY_EXPORTS = {
    "Analytics": (".analytics", "Analytics"),
    "AnalyticsWithResponse": (".analytics", "AnalyticsWithResponse"),
    "AsyncAnalytics": (".analytics", "AsyncAnalytics"),
    "AsyncAnalyticsWithResponse": (".analytics", "AsyncAnalyticsWithResponse"),
    "AsyncBilling": (".organizations", "AsyncBilling"),
    "AsyncBillingWithResponse": (".organizations", "AsyncBillingWithResponse"),
    "AsyncBrands": (".brands", "AsyncBrands"),
    "AsyncBrandsWithResponse": (".brands", "AsyncBrandsWithResponse"),
    "AsyncCitations": (".analytics", "AsyncCitations"),
    "AsyncCitationsWithResponse": (".analytics", "AsyncCitationsWithResponse"),
    "AsyncCompetitors": (".competitors", "AsyncCompetitors"),
    "AsyncCompetitorsWithResponse": (".competitors", "AsyncCompetitorsWithResponse"),
    "AsyncDomains": (".analytics", "AsyncDomains"),
    "AsyncDomainsWithResponse": (".analytics", "AsyncDomainsWithResponse"),
    "AsyncMe": (".identity", "AsyncMe"),
    "AsyncMeWithResponse": (".identity", "AsyncMeWithResponse"),
    "AsyncModels": (".models", "AsyncModels"),
    "AsyncModelsWithResponse": (".models", "AsyncModelsWithResponse"),
    "AsyncOpportunities": (".opportunities", "AsyncOpportunities"),
    "AsyncOpportunitiesWithResponse": (
        ".opportunities",
        "AsyncOpportunitiesWithResponse",
    ),
    "AsyncOrganizations": (".organizations", "AsyncOrganizations"),
    "AsyncOrganizationsWithResponse": (
        ".organizations",
        "AsyncOrganizationsWithResponse",
    ),
    "AsyncPromptPerformance": (".analytics", "AsyncPromptPerformance"),
    "AsyncPromptPerformanceWithResponse": (
        ".analytics",
        "AsyncPromptPerformanceWithResponse",
    ),
    "AsyncPrompts": (".prompts", "AsyncPrompts"),
    "AsyncPromptsWithResponse": (".prompts", "AsyncPromptsWithResponse"),
    "AsyncQueryFanout": (".analytics", "AsyncQueryFanout"),
    "AsyncQueryFanoutWithResponse": (".analytics", "AsyncQueryFanoutWithResponse"),
    "AsyncReports": (".reports", "AsyncReports"),
    "AsyncReportsWithResponse": (".reports", "AsyncReportsWithResponse"),
    "AsyncRequestOptions": (".shared", "AsyncRequestOptions"),
    "AsyncRuns": (".runs", "AsyncRuns"),
    "AsyncRunsWithResponse": (".runs", "AsyncRunsWithResponse"),
    "AsyncSnapshot": (".snapshots", "AsyncSnapshot"),
    "AsyncSnapshotWithResponse": (".snapshots", "AsyncSnapshotWithResponse"),
    "AsyncTags": (".tags", "AsyncTags"),
    "AsyncTagsWithResponse": (".tags", "AsyncTagsWithResponse"),
    "AsyncTools": (".tools", "AsyncTools"),
    "AsyncToolsWithResponse": (".tools", "AsyncToolsWithResponse"),
    "AsyncURLs": (".analytics", "AsyncURLs"),
    "AsyncURLsWithResponse": (".analytics", "AsyncURLsWithResponse"),
    "Billing": (".organizations", "Billing"),
    "BillingWithResponse": (".organizations", "BillingWithResponse"),
    "Brands": (".brands", "Brands"),
    "BrandsWithResponse": (".brands", "BrandsWithResponse"),
    "Citations": (".analytics", "Citations"),
    "CitationsWithResponse": (".analytics", "CitationsWithResponse"),
    "Competitors": (".competitors", "Competitors"),
    "CompetitorsWithResponse": (".competitors", "CompetitorsWithResponse"),
    "Domains": (".analytics", "Domains"),
    "DomainsWithResponse": (".analytics", "DomainsWithResponse"),
    "Me": (".identity", "Me"),
    "MeWithResponse": (".identity", "MeWithResponse"),
    "Models": (".models", "Models"),
    "ModelsWithResponse": (".models", "ModelsWithResponse"),
    "Opportunities": (".opportunities", "Opportunities"),
    "OpportunitiesWithResponse": (".opportunities", "OpportunitiesWithResponse"),
    "Organizations": (".organizations", "Organizations"),
    "OrganizationsWithResponse": (".organizations", "OrganizationsWithResponse"),
    "PromptPerformance": (".analytics", "PromptPerformance"),
    "PromptPerformanceWithResponse": (".analytics", "PromptPerformanceWithResponse"),
    "Prompts": (".prompts", "Prompts"),
    "PromptsWithResponse": (".prompts", "PromptsWithResponse"),
    "QueryFanout": (".analytics", "QueryFanout"),
    "QueryFanoutWithResponse": (".analytics", "QueryFanoutWithResponse"),
    "Reports": (".reports", "Reports"),
    "ReportsWithResponse": (".reports", "ReportsWithResponse"),
    "RequestOptions": (".shared", "RequestOptions"),
    "Runs": (".runs", "Runs"),
    "RunsWithResponse": (".runs", "RunsWithResponse"),
    "Snapshot": (".snapshots", "Snapshot"),
    "SnapshotWithResponse": (".snapshots", "SnapshotWithResponse"),
    "Tags": (".tags", "Tags"),
    "TagsWithResponse": (".tags", "TagsWithResponse"),
    "Tools": (".tools", "Tools"),
    "ToolsWithResponse": (".tools", "ToolsWithResponse"),
    "URLs": (".analytics", "URLs"),
    "URLsWithResponse": (".analytics", "URLsWithResponse"),
}


if not TYPE_CHECKING:

    def __getattr__(name: str) -> object:
        if name not in _LAZY_EXPORTS:
            raise AttributeError(f"module {__name__} has no attribute {name}")
        module, attribute = _LAZY_EXPORTS[name]
        value = getattr(import_module(module, __name__), attribute)
        globals()[name] = value
        return value


def __dir__() -> list[str]:
    return list(__all__)
